# Jammit config:
# http://documentcloud.github.com/jammit/
# example: http://gist.github.com/237848

package_assets: on # (on, off, always)
embed_assets: on # (on, off, datauri)
compress_assets: on # (on, off)
gzip_assets: on # (on, off)
#template_function: _.template # (defaults to the built-in micro-templating)
#package_path: assets # (defaults to assets)
javascript_compressor: yui # (yui, closure)
#compressor_options:
#  compilation_level: ADVANCED_OPTIMIZATIONS
  
javascripts:
# head scripts are required in the head, all others should be at the end of the page
# modernizer provides html5 support checking, etc
# jquery may be referenced by js tha tis in the body, rather than at the end
  head_scripts:
    - public/javascripts/modernizer.js
    
# NOTE: application.js before the other non-rails js libs (so you can call log() etc)    
  end_scripts:
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/jquery.form.js
    - public/javascripts/gallery/jquery.ad-gallery.js
    - public/javascripts/gallery/jquery.create.js

stylesheets:
  screen:
    - public/stylesheets/screen.css
#    - public/stylesheets/gallery.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/ie.css
  handheld:
    - public/stylesheets/handheld.css
